### PR TITLE
Update to the new harfbuzz 2.0.2 release.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Version 0.3 of `harfbuzz-sys` hadn't yet been published, so no
need to bump that.

The `harfbuzz` crate version still needed to be bumped.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/122)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
2.0.2 is out now, so I'll update this PR soon for that ...

**Comment by waywardmonkeys** [comment]
2.0.2 is out now, so I'll update this PR soon for that ...

**Comment by waywardmonkeys** [comment]
2.0.2 is out now, so I'll update this PR soon for that ...

**Comment by waywardmonkeys** [comment]
Harfbuzz 2.0.2 was released already, so I'll update this shortly.

**Comment by waywardmonkeys** [comment]
This has now been updated for the Harfbuzz 2.0.2 release.

**Comment by jdm** [comment]
@bors-servo r-
Homu doesn't think that travis exists for this repo for some reason.

**Pull request merged**
