### PR TITLE
Update to harfbuzz 2.4.0.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/141)

### CODE REVIEW

**Comment by jdm** [comment]
Appveyor is displeased, unfortunately.

**Comment by spl** [comment]
There's a large diff between the [2.4.0 tag](https://github.com/harfbuzz/harfbuzz/releases/tag/2.4.0) and the [2.4.0 tarball](https://github.com/harfbuzz/harfbuzz/releases/download/2.4.0/harfbuzz-2.4.0.tar.bz2). Just the `src/` diff is 98KB. Plus, the 2.4.0 tag [passed AppVeyor](https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/23461953). Can you try again using the repository instead of the tarball?

Also, just for my own personal education, what is the procedure used to make this update? Is it documented anywhere?

**Comment by spl** [comment]
Okay, just discovered https://github.com/harfbuzz/harfbuzz/issues/1641 and https://github.com/harfbuzz/harfbuzz/issues/1643. But there's some implication there that the problematic tarball has been replaced, yet the diff still doesn't make sense.

In particular, there's this diff snippet:

```diff
diff -uar harfbuzz-original/src/hb-iter.hh harfbuzz-2.4.0/src/hb-iter.hh
--- harfbuzz-original/src/hb-iter.hh    2019-04-04 14:17:56.000000000 +0200
+++ harfbuzz-2.4.0/src/hb-iter.hh       2019-03-30 01:16:02.000000000 +0200
[...]
+template<typename T>
+struct _hb_is_iterable<T, hb_bool_tt<true || sizeof (hb_declval (T).iter ())> >
+{ enum { value = true }; };
[...]
```

and that addition exactly matches the first error currently shown in the AppVeyor build log:

```
[harfbuzz-sys 0.3.1] c:\projects\rust-harfbuzz\harfbuzz-sys\harfbuzz\src\hb-iter.hh(205):
error C2228: left of '.iter' must have class/struct/union
[C:\projects\rust-harfbuzz\target\debug\build\harfbuzz-sys-4e2b61eac7e21260\out\build\harfbuzz.vcxproj]
```

**Comment by waywardmonkeys** [comment]
Thanks for looking into this. I've been caught up in other things for the last couple of days.

My process is to grab a new tarball (which includes things that the repo doesn't, like generated configure scripts), and then:

```
cd harfbuzz-sys
git rm -rf harfbuzz
tar -xvf ~/Downloads/harfbuzz-whatever.tar.bz2
mv harfbuzz-whatever harfbuzz
git add harfbuzz
```

Then I'll re-generate the bindings using this:

```
bindgen \
    --no-prepend-enum-name \
    --disable-name-namespacing \
    --distrust-clang-mangling \
    --whitelist-type=hb.* \
    --whitelist-function=hb.* \
    --whitelist-var=HB.* \
    --blacklist-type=HB_VERSION.* \
    -o harfbuzz-sys/src/lib.rs \
    harfbuzz-sys/harfbuzz/src/hb-aat.h \
    -- -DHB_DISABLE_DEPRECATED \
       -Iharfbuzz-sys/harfbuzz/src \
       -I.
```

And then I'll inspect the differences and add the relevant ones. (I skip all documentation changes for now.)

This could all be improved ... but it isn't something that happens all that often.

**Comment by spl** [comment]
A new [2.4.0 tarball](https://github.com/harfbuzz/harfbuzz/releases/download/2.4.0/harfbuzz-2.4.0.tar.bz2) has been uploaded. The diff with the repository looks much better.

**Comment by waywardmonkeys** [comment]
Closing in favor of updating to 2.5.0.

**Pull request closed without merging**
