### PR TITLE
Build harfbuzz crate in CI.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/138)

### CODE REVIEW

**Comment by jdm** [comment]
This does not actually help with #137, but I noticed that we aren't building the harfbuzz crate in CI at all.

**Comment by jdm** [comment]
The latest commit attempts to address #137 by verifying the package creation works with HARFBUZZ_SYS_NO_PKG_CONFIG=1.

**Comment by spl** [comment]
This seems to be along the right lines. Can you unpack the tarball created by `cargo package` and build it?

**Comment by jdm** [comment]
I believe that is already what happens as part of `cargo package`. I'm waiting for CI to confirm this theory.

**Comment by spl** [comment]
Nice. I had to read the `package` documentation quite thoroughly to find where that was mentioned

**Comment by jdm** [comment]
Excellent, `cargo package` breaks in CI, so we can reproduce the problem from #137.

**Comment by jdm** [comment]
Wooo, green build.

**Comment by jdm** [comment]
```
59.22s$ cargo package
   Packaging harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/harfbuzz-sys)
   Verifying harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/harfbuzz-sys)
    Updating crates.io index
   Compiling cc v1.0.32
   Compiling pkg-config v0.3.14
   Compiling libc v0.2.50
   Compiling cmake v0.1.36
   Compiling servo-freetype-sys v4.0.5
   Compiling harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1)
   Compiling freetype v0.4.1
    Finished dev [unoptimized + debuginfo] target(s) in 59.19s
error: failed to verify package tarball
Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR. Modified file: /home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-myanmar-machine.hh
To proceed despite this, pass the `--no-verify` flag.
The command "cargo package" exited with 101.
```

**Comment by spl** [comment]
```
Source directory was modified by build.rs during cargo publish.
Build scripts should not modify anything outside of OUT_DIR.
Modified file: .../harfbuzz/src/hb-ot-shape-complex-myanmar-machine.hh
```

Huh. That's strange. I just `cargo package`d your branch locally: no error and no change in the modification time of `hb-ot-shape-complex-myanmar-machine.hh`.

**Comment by spl** [comment]
I noticed that you have the following in the `.travis.yml` change:

```yaml
env:
 - HARFBUZZ_SYS_NO_PKG_CONFIG: 1
```

I believe this creates a single run with `HARFBUZZ_SYS_NO_PKG_CONFIG=1`. Should you also have an `env` option without `HARFBUZZ_SYS_NO_PKG_CONFIG=1` to test that aspect as well?

**Comment by jdm** [comment]
Continued in #142.

**Pull request closed without merging**
