### PR TITLE
Move freetype binding to separate module.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This makes it more like the others, and will keep it cleaner when we go and bind the other functions in this module.

### CODE REVIEW

**Review by mrobinson — CHANGES_REQUESTED** [review]
This looks fine to me and I like the cleanup. The only issue here is that the new file is missing a license header. I understand that there are many files missing headers, but that's another issue we will need to fix. :)

**Comment by waywardmonkeys** [comment]
Can I just add them all at once in something separate?

**Comment by waywardmonkeys** [comment]
Give me the text you want, and I'll add it.

None of the files in the `harfbuzz-sys` have a copyright / license header. The files in `harfbuzz` do. But the licenses are not the same. The `harfbuzz-sys` crate is MIT, while `harfbuzz` is MIT OR Apache 2.0.

**Comment by waywardmonkeys** [comment]
Okay, added here, and the rest of the files and such updated in #225.

**Review by mrobinson — APPROVED** [review]
Thanks!

**Pull request merged**
