### PR TITLE
Update to harfbuzz 1.9.0

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/120)

### CODE REVIEW

**Comment by nox** [comment]
This is a breaking change.

**Comment by waywardmonkeys** [comment]
@nox: Yes ... in that some things got to be `*const` rather than `*mut`, right?

I have another couple of commits queued up to bump the version to `0.3` and a couple of other tweaks ...

**Comment by waywardmonkeys** [comment]
Added 2 of the commits here for now. The other one is about doc comments and I have to work on it more and probably do some of it upstream first.

**Comment by waywardmonkeys** [comment]
Any thoughts on this apart from it being a breaking change?

**Pull request merged**
