### PR TITLE
Update to harfbuzz 2.7.4

### PR DESCRIPTION
**Pull request by songww**

### CODE REVIEW

**Comment by jdm** [comment]
Mmm, we need to migrate from TravisCI to Github Actions before we can verify that these changes work.

**Comment by jdm** [comment]
https://github.com/servo/rust-harfbuzz/pull/192

**Comment by songww** [comment]
Ok, I am trying to migrate to meson build

**Comment by songww** [comment]
I have no idea that why windows test failed.

**Comment by jdm** [comment]
You may need to add the same windows flags to the sys-test build via https://docs.rs/ctest/latest/ctest/struct.TestGenerator.html#method.flag (https://github.com/servo/rust-harfbuzz/blob/master/harfbuzz-sys-test/build.rs)

**Comment by alerque** [comment]
Why is all this Harfbuzz code vendored and tracked in source control here? That seems ... a lot less than ideal. Also 2.7.4 is just about as fresh as Ubuntu LTS these days — somewhere more recent than the dinosaurs but older than the trees.

**Comment by songww** [comment]
> Also 2.7.4 is just about as fresh as Ubuntu LTS these days — somewhere more recent than the dinosaurs but older than the trees.

Because the previous version was 2.6.x, the upgrade to 2.7.4 had many less changes than the newer version. And 2.7 is the first version after migration to meson.

Plan to migrate to meson and then upgrade to a newer version

**Comment by songww** [comment]
@jdm   tests passed

**Comment by songww** [comment]
Thanks

**Pull request merged**
