### PR TITLE
Update to harfbuzz 2.6.0.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/161)

### CODE REVIEW

**Comment by jdm** [comment]
The macOS shared library CI configuration is reporting errors but not the static library configuration for some reason:
```
cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7516:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_ROMAN_val = HB_OT_LAYOUT_BASELINE_TAG_ROMAN;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7516:105: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_ROMAN'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_ROMAN_val = HB_OT_LAYOUT_BASELINE_TAG_ROMAN;

cargo:warning=                                                                                                        ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7517:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_ROMAN(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7522:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_HANGING_val = HB_OT_LAYOUT_BASELINE_TAG_HANGING;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7522:107: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_HANGING'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_HANGING_val = HB_OT_LAYOUT_BASELINE_TAG_HANGING;

cargo:warning=                                                                                                          ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7523:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_HANGING(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7528:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7528:124: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT;

cargo:warning=                                                                                                                           ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7529:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7534:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7534:122: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT;

cargo:warning=                                                                                                                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7535:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7540:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7540:125: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT;

cargo:warning=                                                                                                                            ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7541:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7546:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT;

cargo:warning=                         ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7546:123: error: use of undeclared identifier 'HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT_val = HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT;

cargo:warning=                                                                                                                          ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7547:20: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=             const hb_ot_layout_baseline_tag_t* __test_const_HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT(void) {

cargo:warning=                   ^

cargo:warning=/Users/travis/build/servo/rust-harfbuzz/target/debug/build/harfbuzz-sys-test-e44a89623ef40388/out/all.c:7552:26: error: unknown type name 'hb_ot_layout_baseline_tag_t'

cargo:warning=            static const hb_ot_layout_baseline_tag_t __test_const_HB_OT_LAYOUT_BASELINE_TAG_MATH_val = HB_OT_LAYOUT_BASELINE_TAG_MATH;

cargo:warning=                         ^

cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]

cargo:warning=20 errors generated.

exit code: 1

--- stderr

rust version: 1.37.0


```

**Comment by waywardmonkeys** [comment]
The shared build is trying to build against harfbuzz 2.4 from homebrew (which is odd, since my homebrew says it has 2.5.3). It is true that homebrew doesn't have 2.6.0 yet, and so that is at least part of this failure.

**Comment by jdm** [comment]
You could try adding `brew update` to the travis CI steps, since the docs say "The Homebrew addon uses the Homebrew database on the build image by default, but can be configured to run brew update if needed."

**Comment by waywardmonkeys** [comment]
I'm trying a different approach here. If this works, then I'll do a new PR with that by itself, and then a new PR for updating to Harfbuzz 1.6.1 instead.

**Pull request closed without merging**
