### PR TITLE
Switch to a submodule for harfbuzz.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This simplifies updating as well as reducing the amount of churn in this repo when updating.

This doesn't change the version used or anything yet, it should just be a straight swap from extracted sources to using a submodule.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I guess this is at least good for discussion ... I think this is the right direction to take.

We'll have to fix the one CI task though.

**Comment by mrobinson** [comment]
It looks like the CI error is:

```
Run make -f harfbuzz-sys/makefile.touch touch HARFBUZZ=harfbuzz-sys/harfbuzz
harfbuzz-sys/makefile.touch:9: *** 'configure' not found in path given by $HARFBUZZ: harfbuzz-sys/harfbuzz.  Stop.
```

Does the build script need to run autoconf?

**Comment by waywardmonkeys** [comment]
In theory, we have to switch to running `meson` to do that build.

But that build is used so that we can test linking against harfbuzz on the system and controlling what version it is.

An alternative is that we just link against what is on the system and not always provide new API. `ubuntu-latest` provides harfbuzz 2.7.4, I think ... same as what we're currently bundling.

on macOS, we use what is in homebrew, which tends to be fairly current.

on Windows, we don't perform this action and only test using the bundled one in our CI, I think.

**Comment by waywardmonkeys** [comment]
My plan was to circle back around to this once we had features re-worked and other things improved ... as that helps make it more clear what exactly we're checking in each scenario.

The other harfbuzz bindings always essentially copy our existing logic: Unless a special env var is set, look for one on the system and use it, otherwise, build the bundled copy.

But it doesn't bother testing nearly as much in CI.

**Review by mrobinson — CHANGES_REQUESTED** [review]
This is a really nice change. The one I want to suggest here is a small note in the README letting folks know that they should do a `git submodule init` when checking out the source.

**Comment by waywardmonkeys** [comment]
@mrobinson Okay, update to the `README.md` added.

**Comment by waywardmonkeys** [comment]
@jdm Could you land this one too while you are at it, please?

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
