### PR TITLE
Add bindgen feature.

### PR DESCRIPTION
**Pull request by songww**
* Run bindgen at build time to support any version.
* Replace ctest2 with ctest to support nightly builds.
* Bindgen test with harfbuzz latest on macOS.

### CODE REVIEW

**Comment by songww** [comment]
Hi @jdm  , how about this?

**Comment by jdm** [comment]
A couple questions:
* what's the motivation for this change?
* why is it useful to support both bindgen and non-bindgen modes?

**Comment by bennyboer** [comment]
Anyone knows why it wasn't done using `bindgen` in the first place?

**Comment by jdm** [comment]
This crate was written before bindgen existed.

**Comment by songww** [comment]
最好是跟随harfbuzz更新我们的bindings,并对每个版本变更的api添加feature标记，通过这些版本的feature让其针对较低的版本亦可连接使用，且这样能容易的包装安全的api。但是如果全部使用bindgen动态生成的话，对于包装safe api的crate来说，判断harfbuzz的版本就成了难题，而且某些api是否可用更无从得知。

**Comment by waywardmonkeys** [comment]
As @songww says, we won't be able to auto-generate the bindings repeatedly going forward as we will be using features to gate access to the stuff from different versions of harfbuzz.

**Pull request closed without merging**
