### PR TITLE
Release version 0.6.0 of all crates

### PR DESCRIPTION
**Pull request by mrobinson**
This updates the version and syncs them in preparation for a new
release.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
The traits crate will need a release too but not a version bump. Right?

**Comment by mrobinson** [comment]
> The traits crate will need a release too but not a version bump. Right?

Oh, excellent point. I'm going to sync up the version of all of these so that it is easier to track things. Let's version all of the libraries together.

**Comment by mrobinson** [comment]
https://github.com/servo/rust-harfbuzz/issues/235 will have to be fixed before we can land this and do a release.

**Comment by waywardmonkeys** [comment]
After this release, the traits crate should be versioned independently, I think. @Manishearth @sffc

**Comment by atouchet** [comment]
Could #202 be merged as well if there's going to be a version bump?

**Review by Manishearth — APPROVED** [review]
Anything you need to help move this along?

**Comment by mrobinson** [comment]
Sorry for the lag here. I'll land this one now. I think everything blocking it has landed.

**Pull request merged**
