### PR TITLE
Release 0.3.1.

### PR DESCRIPTION
**Pull request by jdm**
This includes #126 and #127 which only add new APIs, and #129 which adds new features but uses them by default.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/130)

### CODE REVIEW

**Comment by kpozin** [comment]
Is this ready for release?

**Comment by kpozin** [comment]
Is there anything else blocking the release to crates.io?

**Comment by jdm** [comment]
Ack, sorry.

**Comment by jdm** [comment]
Released.

**Comment by jdm** [comment]
Sorry, spoke too soon. The current crate is too big to upload; I need to figure out what to do about it.

**Comment by jdm** [comment]
Published.

**Pull request merged**
