### PR TITLE
Up to harfbuzz v7.1.0

### PR DESCRIPTION
**Pull request by songww**

### CODE REVIEW

**Comment by yisibl** [comment]
Hi, do you plan to upgrade to the latest v7.x?

**Comment by yisibl** [comment]
is there any difference between harfbuzz-sys and [harfbuzz-bindings](https://github.com/bennyboer/harfbuzz-bindings)?

**Comment by songww** [comment]
> Is there any difference between harfbuzz-sys and [harfbuzz-bindings](https://github.com/bennyboer/harfbuzz-bindings)?

It seems that harfbuzz only supports the version installed by vcpkg on Windows, but this package does not have this restriction.

**Comment by yisibl** [comment]
@songww No, it's cross platform

**Comment by yisibl** [comment]
The [harfbuzz_rs]( https://github.com/harfbuzz/harfbuzz_rs) project is now maintained by the Harfbuzz team!

**Comment by mrobinson** [comment]
Thanks for this change. Some of this could be repurposed perhaps (as it seems to do more than simply update HarfBuzz), but the update of the version of HarfBuzz is accomplished in #237.

**Pull request closed without merging**
