### PR TITLE
[breaking change] Stop exporting libc and cpp definitions.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
These definitions aren't needed and are just a relic of how bindgen
works. They shouldn't be exported and since they aren't used, they
don't need to exist.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/86)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Ping? I would like to submit a PR that logically comes after this one so that there is no conflict.

**Comment by mbrubeck** [comment]
I'd like to get out of the habit of editing generated code (though I'm guilty of it myself), and instead use bindgen options to control the output when it is generated.  Would you be interested in adding a bindgen script (it could be a simple shell script or similar), which we can then tweak to blacklist items that we don't want?

**Comment by waywardmonkeys** [comment]
The extra types involved are different on each platform which makes it a bit trickier.

I had been thinking of adding doc comments to this as well so that the Rust docs are more usable. (It ends up that Harfbuzz docs themselves are a bit scattered.) I have done this with some of my own crates where I don’t keep running bindgen. This also comes into play with enums and bitflags.

**Comment by mbrubeck** [comment]
Yeah, that makes sense.  Any thoughts about how to handle regenerating bindings (e.g. for harfbuzz upgrades)?  Maybe we should have a separate branch that just has the generated bindings, and merge that into the master branch (which includes patches to the bindings) whenever it changes.

**Comment by mbrubeck** [comment]
Merging this for now; we can deal with the code generation issue later.

**Pull request merged**
