### PR TITLE
Update harfbuzz 1.7.4

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Fixes issue #89.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/99)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This might be interesting to see how it deals with Windows.

**Comment by jdm** [comment]
We should probably add appveyor integration, in that case. @larsbergstrom could you flip that switch?

**Comment by larsbergstrom** [comment]
@jdm Appveyor is now enabled for this repository.

**Comment by jdm** [comment]
I've opened https://github.com/servo/rust-harfbuzz/pull/100.

**Comment by waywardmonkeys** [comment]
This is waiting for #100 to land and then once we know this works on Windows, it can hopefully land?

**Comment by jdm** [comment]
Yes, that's fine from my perspective.

**Comment by jdm** [comment]
@waywardmonkeys Could you rebase and push so this gets an appveyor run?

**Comment by waywardmonkeys** [comment]
@jdm Done.

**Comment by waywardmonkeys** [comment]
The upstream 1.7.4 release is apparently broken for `cmake` builds ... I'll submit a fix upstream and then add the missing file here and re-force push. (Probably in about an hour.)

**Pull request merged**
