### PR TITLE
Move touch command into makefile.cargo

### LINKED ISSUE #54: Build error: "'aclocal-1.14' is missing on your system."
`cargo build` runs fine on my machine, but in `cargo build --target arm-linux-androideabi` the build script fails with stderr as below. What’s `aclocal-1.14`? Do I need to install something?

CC @larsbergstrom @mbrubeck 

```
make[1]: warning: -jN forced in submake: disabling jobserver mode.
/home/simon/projects/servo/deps/rust-harfbuzz/harfbuzz-sys/harfbuzz/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [/home/simon/projects/servo/deps/rust-harfbuzz/harfbuzz-sys/harfbuzz/aclocal.m4] Error 127
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #54, fixes servo/servo#8890.

r? @larsbergstrom or @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/58)

### CODE REVIEW

**Comment by mbrubeck** [comment]
I worried in #54 that this change might cause spurious re-compiles, but in my testing it does not.

**Comment by mbrubeck** [comment]
…and the Travis build failed with `aclocal-1.14: command not found`.  Great.

**Comment by mbrubeck** [comment]
I forgot to escape the braces in the makefile.  When I fix it, the build succeeds but it *does* cause spurious rebuilds.  So I'll need to make it smarter.

**Comment by mbrubeck** [comment]
Updated to fix the Makefile command and to ensure that the `touch` command runs only once.  This will still cause one extra re-build in many cases, but the extra build is very fast because it doesn't actually re-compile Harfbuzz.  (So the first `cargo build` causes a full compile; the second one causes a fast no-op build; and the third one correctly does nothing at all.)

I can't think of any way of totally eliminating the spurious re-build.

**Comment by metajack** [comment]
Have you tried just removing the generated files and running autogen as the first step?

**Comment by mbrubeck** [comment]
> Have you tried just removing the generated files and running autogen as the first step?

That should work, though Harfbuzz’s `autogen.sh` depends on both autoconf and [Ragel](http://www.colm.net/open-source/ragel/), which would add two new prerequisites to the Servo build.  Installing Ragel would be an additional (but small) hassle for Windows users.

**Comment by mbrubeck** [comment]
> Have you tried just removing the generated files and running autogen as the first step?

I implemented this, and it has the same problems as the current PR.  `autogen.sh` touches several dozen files in the source directory, and the timestamps of these generated files cause Cargo to re-run the build script.

However, I found that adding an explicit `exclude` list to `Cargo.toml` fixes the problem of extra rebuilds.  I've updated my original PR to add this.  r? @metajack 

(We could additionally remove all the generated files from the tree and run `autogen.sh`, but this requires a much larger `exclude` list and also adds new build dependencies.)

**Comment by manfredbrandl** [comment]
@metajack is there still a problem with this PR?

**Comment by metajack** [comment]
@bors-servo r+

Thanks for dealing with this. autotools stuff is never fun.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-harfbuzz/58#-:-K9mIqnInRP3cRsGxUAj:-1931043101)*

**Pull request merged**
