### PR TITLE
Limit test data excluded and support HARFBUZZ_SYS_NO_PKG_CONFIG better

### PR DESCRIPTION
**Pull request by spl**
* This is an alternative to #138 that builds on the work there.
* I added better support for `HARFBUZZ_SYS_NO_PKG_CONFIG` being `0` or `1`.
* I expanded the Travis-CI test matrix to test the above as well as add `osx`.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/142)

### CODE REVIEW

**Comment by spl** [comment]
I don't understand the error.

On the [PR build (`HARFBUZZ_SYS_NO_PKG_CONFIG="1"`)](https://travis-ci.com/servo/rust-harfbuzz/jobs/189681406):

```
$ cargo package --manifest-path=harfbuzz-sys/Cargo.toml
error: 1 files in the working directory contain changes that were not yet committed into git:

harfbuzz/src/hb-ot-shape-complex-use-machine.hh

to proceed despite this, pass the `--allow-dirty` flag

The command "cargo package --manifest-path=harfbuzz-sys/Cargo.toml" exited with 101.
```

On [my build of the same](https://travis-ci.org/spl/rust-harfbuzz/jobs/514702924):

```
$ cargo package --manifest-path=harfbuzz-sys/Cargo.toml
   Packaging harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/harfbuzz-sys)
   Verifying harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/harfbuzz-sys)
    Updating crates.io index
   Compiling cc v1.0.32
   Compiling pkg-config v0.3.14
   Compiling libc v0.2.51
   Compiling cmake v0.1.37
   Compiling servo-freetype-sys v4.0.5
   Compiling harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1)
   Compiling freetype v0.4.1
    Finished dev [unoptimized + debuginfo] target(s) in 58.07s
The command "cargo package --manifest-path=harfbuzz-sys/Cargo.toml" exited with 0.
```

Is this a Travis-CI cache issue of some sort?

**Comment by spl** [comment]
The PR is on travis-ci.com, and mine is on travis-ci.org. Does that make a difference?

**Comment by jdm** [comment]
That's the same error that I saw on my PR for one of the CI builds (the other passed). I don't know what to make of it.

**Comment by spl** [comment]
At least now something's happening on both travis-ci.com and travis-ci.org:

<https://travis-ci.com/servo/rust-harfbuzz/jobs/189894765> (`HARFBUZZ_SYS_NO_PKG_CONFIG="1"`):

```
$ cargo package --manifest-path=harfbuzz-sys/Cargo.toml
   Packaging harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/harfbuzz-sys)
   Verifying harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/harfbuzz-sys)
    Updating crates.io index
   Compiling cc v1.0.34
   Compiling pkg-config v0.3.14
   Compiling libc v0.2.51
   Compiling cmake v0.1.37
   Compiling servo-freetype-sys v4.0.5
   Compiling harfbuzz-sys v0.3.1 (/home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1)
   Compiling freetype v0.4.1
    Finished dev [unoptimized + debuginfo] target(s) in 57.88s
error: failed to verify package tarball
Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR. Modified file: /home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-use-machine.hh
To proceed despite this, pass the `--no-verify` flag.
The command "cargo package --manifest-path=harfbuzz-sys/Cargo.toml" exited with 101.
```

<https://travis-ci.org/spl/rust-harfbuzz/jobs/515032933> (`HARFBUZZ_SYS_NO_PKG_CONFIG="0"`):

```
$ cargo package --manifest-path=harfbuzz-sys/Cargo.toml
   Packaging harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/harfbuzz-sys)
   Verifying harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/harfbuzz-sys)
    Updating crates.io index
   Compiling cc v1.0.34
   Compiling pkg-config v0.3.14
   Compiling libc v0.2.51
   Compiling cmake v0.1.37
   Compiling servo-freetype-sys v4.0.5
   Compiling harfbuzz-sys v0.3.1 (/home/travis/build/spl/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1)
   Compiling freetype v0.4.1
    Finished dev [unoptimized + debuginfo] target(s) in 58.55s
error: failed to verify package tarball
Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR. Modified file: /home/travis/build/spl/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1/harfbuzz/util/ansi-print.cc
To proceed despite this, pass the `--no-verify` flag.
The command "cargo package --manifest-path=harfbuzz-sys/Cargo.toml" exited with 101.
```

**Comment by spl** [comment]
Well, at least I can confirm that the last modified file time does change. Not yet sure if that's useful, but it seems to imply that `cargo package` is failing for a valid reason.

```
[2019-04-03T08:00:55Z TRACE cargo::sources::path] last modified file /home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1: 1554278454.221515537s
...
[2019-04-03T08:01:50Z TRACE cargo::sources::path] last modified file /home/travis/build/servo/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1: 1554278467.852523536s
```

1554278467.852523536 - 1554278454.221515537 = 13.63100791 seconds

**Comment by spl** [comment]
Now, when I see:

```
error: failed to verify package tarball
Caused by:
Source directory was modified by build.rs during cargo publish.
Build scripts should not modify anything outside of OUT_DIR.
Modified file:
.../target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-myanmar-machine.hh
```

I can confirm that its file modification time changed (and no non-`Makefile` modification time changed):

```diff
-[harfbuzz-sys 0.3.1] -rw-rw-r-- 1 travis travis  12409 2019-04-03 11:36:22.227032921 +0000 hb-ot-shape-complex-myanmar-machine.hh
+[harfbuzz-sys 0.3.1] -rw-rw-r-- 1 travis travis  12409 2019-04-03 11:36:36.647224654 +0000 hb-ot-shape-complex-myanmar-machine.hh
```

and no content changed:

```
$ diff -r harfbuzz-sys/harfbuzz target/package/harfbuzz-sys-0.3.1/harfbuzz || true
Only in harfbuzz-sys/harfbuzz/test/fuzzing: fonts
Only in harfbuzz-sys/harfbuzz/test/shaping/data/aots: fonts
Only in harfbuzz-sys/harfbuzz/test/shaping/data/in-house: fonts
Only in harfbuzz-sys/harfbuzz/test/shaping/data/text-rendering-tests: fonts
Only in harfbuzz-sys/harfbuzz/test/subset/data: fonts
```

Unfortunately, this particular error and every other one appears nondeterministically.

**Comment by spl** [comment]
Just to prove my point, triggering a rebuild in 4a6d69a caused the error to go away.

**Comment by spl** [comment]
I'm at a loss. Sometimes, it's `util/ansi-print.cc`, as in 3b148db. Other times, it's `src/hb-ot-shape-complex-myanmar-machine.h` or `src/hb-ot-shape-complex-use-machine.hh`. Sometimes, it's `HARFBUZZ_SYS_NO_PKG_CONFIG=0`, other times it's `HARFBUZZ_SYS_NO_PKG_CONFIG=1`. And, finally, sometimes, there's no issue at all. 😱

**Comment by spl** [comment]
In looking at [one of the builds](https://travis-ci.org/spl/rust-harfbuzz/jobs/515145452) again, I noticed the following (abbreviated). Can you spot the differences?

```diff
diff -r harfbuzz-sys/harfbuzz/src/hb-ot-shape-complex-use-machine.hh target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-use-machine.hh
39,45c39,45
< 	12u, 44u, 1u, 15u, 1u, 1u, 12u, 44u, 0u, 44u, 21u, 21u, 8u, 44u, 8u, 44u,
< 	1u, 15u, 1u, 1u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u,
< 	8u, 39u, 8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u,
< 	8u, 44u, 8u, 44u, 8u, 44u, 1u, 39u, 8u, 44u, 13u, 21u, 4u, 4u, 13u, 13u,
< 	8u, 44u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 8u, 39u,
< 	8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u,
< 	8u, 44u, 8u, 44u, 1u, 39u, 1u, 15u, 12u, 44u, 1u, 44u, 8u, 44u, 21u, 42u,
---
> 	12u, 44u, 1u, 15u, 1u, 1u, 12u, 44u, 0u, 44u, 21u, 21u, 8u, 44u, 8u, 44u, 
> 	1u, 15u, 1u, 1u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 
> 	8u, 39u, 8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 
> 	8u, 44u, 8u, 44u, 8u, 44u, 1u, 39u, 8u, 44u, 13u, 21u, 4u, 4u, 13u, 13u, 
> 	8u, 44u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 8u, 39u, 
> 	8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 
> 	8u, 44u, 8u, 44u, 1u, 39u, 1u, 15u, 12u, 44u, 1u, 44u, 8u, 44u, 21u, 42u, 
50,56c50,56
< 	33, 15, 1, 33, 45, 1, 37, 37,
< 	15, 1, 37, 37, 32, 19, 19, 19,
< 	32, 32, 32, 37, 37, 37, 37, 37,
< 	37, 37, 37, 39, 37, 9, 1, 1,
< 	37, 37, 37, 32, 19, 19, 19, 32,
< 	32, 32, 37, 37, 37, 37, 37, 37,
< 	37, 37, 39, 15, 33, 44, 37, 22,
---
> 	33, 15, 1, 33, 45, 1, 37, 37, 
> 	15, 1, 37, 37, 32, 19, 19, 19, 
> 	32, 32, 32, 37, 37, 37, 37, 37, 
> 	37, 37, 37, 39, 37, 9, 1, 1, 
> 	37, 37, 37, 32, 19, 19, 19, 32, 
> 	32, 32, 37, 37, 37, 37, 37, 37, 
> 	37, 37, 39, 15, 33, 44, 37, 22, 
```

**Comment by KiChjang** [comment]
@spl I see the additional whitespace after every line in the diff, is that intended?

**Comment by spl** [comment]
@KiChjang I hope it's not intended. I don't know where it's coming from or why it only happens occasionally. My only guess is that the HarfBuzz build process (i.e. configure/make) is doing something very strange.

**Comment by spl** [comment]
On a whim, I'm trying `cargo` from `master`.

**Comment by spl** [comment]
Arg, still [failing](https://travis-ci.org/spl/rust-harfbuzz/jobs/516131676):

```
error: failed to verify package tarball
Caused by:
Source directory was modified by build.rs during cargo publish.
Build scripts should not modify anything outside of OUT_DIR.
Changed: /home/travis/build/spl/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-use-machine.hh
```

```diff
181c181
< -rw-rw-r-- 1 travis travis  15681 2019-04-05 11:00:11.463369110 +0000 hb-ot-shape-complex-use-machine.hh
---
> -rw-rw-r-- 1 travis travis  15927 2019-04-05 11:00:25.643405312 +0000 hb-ot-shape-complex-use-machine.hh
```

```diff
diff -r harfbuzz-sys/harfbuzz/src/hb-ot-shape-complex-use-machine.hh target/package/harfbuzz-sys-0.3.1/harfbuzz/src/hb-ot-shape-complex-use-machine.hh
39,45c39,45
< 	12u, 44u, 1u, 15u, 1u, 1u, 12u, 44u, 0u, 44u, 21u, 21u, 8u, 44u, 8u, 44u,
< 	1u, 15u, 1u, 1u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u,
< 	8u, 39u, 8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u,
< 	8u, 44u, 8u, 44u, 8u, 44u, 1u, 39u, 8u, 44u, 13u, 21u, 4u, 4u, 13u, 13u,
< 	8u, 44u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 8u, 39u,
< 	8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u,
< 	8u, 44u, 8u, 44u, 1u, 39u, 1u, 15u, 12u, 44u, 1u, 44u, 8u, 44u, 21u, 42u,
---
> 	12u, 44u, 1u, 15u, 1u, 1u, 12u, 44u, 0u, 44u, 21u, 21u, 8u, 44u, 8u, 44u, 
> 	1u, 15u, 1u, 1u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 
> 	8u, 39u, 8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 
> 	8u, 44u, 8u, 44u, 8u, 44u, 1u, 39u, 8u, 44u, 13u, 21u, 4u, 4u, 13u, 13u, 
> 	8u, 44u, 8u, 44u, 8u, 44u, 8u, 39u, 8u, 26u, 8u, 26u, 8u, 26u, 8u, 39u, 
> 	8u, 39u, 8u, 39u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 8u, 44u, 
> 	8u, 44u, 8u, 44u, 1u, 39u, 1u, 15u, 12u, 44u, 1u, 44u, 8u, 44u, 21u, 42u, 
[...]
```

There goes my theory that it was a `cargo` bug that was fixed! 🙄

**Comment by fasihrana** [comment]
This just caused an issue for me publishing my own dependent crate to crates.io. I don't see an issue when building binaries, but this shows up in `cargo package` on [fasihrana/skryn](https://github.com/fasihrana/skryn)

**Comment by spl** [comment]
> This just caused an issue for me publishing my own dependent crate to crates.io. I don't see an issue when building binaries, but this shows up in `cargo package` on [fasihrana/skryn](https://github.com/fasihrana/skryn)

@fasihrana I think you're referring to #137, which was fixed in #144, and that was merged to `master` 2 days ago. I think @jdm is going to make a release soon.

This particular PR started as a fix for #137 but has since become an attempt to figure out yet another, more elusive issue with `cargo package`.

**Comment by fasihrana** [comment]
> @fasihrana I think you're referring to #137, which was fixed in #144, and that was merged to `master` 2 days ago. I think @jdm is going to make a release soon.

Thank you. I'll update my crate once that is released.

**Comment by spl** [comment]
While this was a interesting (and challenging) experiment to determine why sporadic and spurious errors were appearing when running `cargo package` on Travis, I can no longer reproduce these errors in the test matrix of #146. Since #144 already included the key part of this PR and #146 has a better setup, I'm closing this.

**Comment by spl** [comment]
Correction: The `cargo package` errors seen here are still apparent in #146. I unknowingly hid them behind `after_script`, a part of the job lifecycle whose errors do not affect the build status. That said, there is still nothing in this PR that warrants keeping it open.

**Pull request closed without merging**
