### PR TITLE
Experimental change to use harfbuzz unity build.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is a test to see what happens if we switch to using the unity build for harfbuzz.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/170)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@jdm I think my only real concern about this at this point is how things are on Android since the build system has changed entirely ...

(And that I need to amend the commit to have a better message)

**Comment by jrmuizel** [comment]
@waywardmonkeys are you going to test on Android?

**Comment by waywardmonkeys** [comment]
@jrmuizel How would I test on Android? (I don't do any Android work ...)

Is that something that @bors-servo can do?

**Comment by waywardmonkeys** [comment]
I forgot to add a change to my commit. :( Testing again ...

**Comment by waywardmonkeys** [comment]
@jdm Let's move forward on merging this?

This would have avoided the issue that @SimonSapin had as well ... in addition to improving our builds for iOS and WebAssembly.

**Comment by jdm** [comment]
@waywardmonkeys Are the only concerns about whether this will break the build on android? If so, it would be straightforward to add a patch to https://github.com/servo/servo/blob/master/Cargo.toml to use this branch and send it through our CI to verify that everything still builds.

**Comment by waywardmonkeys** [comment]
That is my only concern, yes.

**Comment by jdm** [comment]
Getting build results from https://github.com/servo/servo/pull/24784.

**Comment by jdm** [comment]
@bors-servo r+
Looks good!

**Comment by waywardmonkeys** [comment]
Thanks!

**Pull request merged**
