### PR TITLE
Build with clang on ARM/Android

### PR DESCRIPTION
**Pull request by asajeffrey**
Makes it possible to build with clang for Android.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/119)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Any chance that just using the cmake build for `harfbuzz` would be fine / easier for Android? I'd actually just like to consider doing that for all platforms as a simplification of the build process.

**Comment by jdm** [comment]
It would be nice to move to that, but I would prefer not to make these changes wait on investigating it. We're already juggling a number of dependencies and toolchain changes as part of the upstream Servo change that requires these ones.

**Pull request merged**
