### PR TITLE
[breaking change] Use ::std::os::raw instead of libc.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is a breaking change.

Fixes issue #88.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-harfbuzz/91)

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
After this, I can do the update of `harfbuzz` to 1.7.x and re-generate with `bindgen` and hopefully be closer to using the `bindgen` output again, but this will help to minimize the diff and separate changes out.

**Comment by mbrubeck** [comment]
@bors-servo retry

* Travis build was canceled?

**Comment by waywardmonkeys** [comment]
Thanks!

**Pull request merged**
